baseURL = 'https://example.org/'
languageCode = 'ja-JP'
title = 'Hugo theme JIRA issues'

[menus]
  [[menus.main]]
    name = 'projects'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'tags'
    pageRef = '/tags'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
